# Generated by Django 3.0.5 on 2020-05-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.CharField(max_length=100)),
                ('jugador', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
                ('tiempo', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['tiempo'],
            },
        ),
    ]
